version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: bibliotheque_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bibliotheque
      MYSQL_USER: bibliotheque_user
      MYSQL_PASSWORD: bibliotheque_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - bibliotheque_network

  # API Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bibliotheque_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: mysql
      DB_USER: bibliotheque_user
      DB_PASSWORD: bibliotheque_password
      DB_NAME: bibliotheque
      JWT_SECRET: votre_secret_jwt_super_securise_production
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - bibliotheque_network
    volumes:
      - ./backend/uploads:/app/uploads

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bibliotheque_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bibliotheque_network

volumes:
  mysql_data:

networks:
  bibliotheque_network:
    driver: bridge
